$ErrorActionPreference='Stop'
$f = Join-Path $PSScriptRoot 'Assets\Scripts\Editor\Alsasua.Editor.asmdef'
$json = @'
{
    "name": "Alsasua.Editor",
    "rootNamespace": "",
    "references": [
        "Alsasua.Core",
        "Alsasua.Runtime",
        "Alsasua.Modules",
        "Alsasua.Systems",
        "CesiumForUnity",
        "DelaunayER",
        "Den.Tools",
        "EasyRoads3Dv3",
        "MapMagic",
        "Newtonsoft.Json",
        "Unity.Burst",
        "Unity.Cinemachine",
        "Unity.Collections",
        "Unity.InputSystem",
        "Unity.InputSystem.ForUI",
        "Unity.Mathematics",
        "Unity.ProBuilder",
        "Unity.RenderPipelines.Core.Runtime",
        "Unity.RenderPipelines.Core.Runtime.Shared",
        "Unity.RenderPipelines.GPUDriven.Runtime",
        "Unity.RenderPipelines.HighDefinition.Config.Runtime",
        "Unity.RenderPipelines.HighDefinition.Runtime",
        "Unity.Services.Core",
        "Unity.Splines",
        "Unity.TerrainTools",
        "Unity.TextMeshPro",
        "Unity.Timeline",
        "Unity.UnifiedRayTracing.Runtime",
        "Unity.VisualEffectGraph.Runtime",
        "Unity.VisualScripting.Core",
        "Unity.VisualScripting.Flow",
        "ALP8310_ControllerGlobal",
        "Autodesk.Fbx",
        "Unity.Formats.Fbx.Runtime",
        "Unity.Multiplayer.Center.Common",
        "Unity.RenderPipelines.Core.Editor",
        "Unity.RenderPipelines.HighDefinition.Editor",
        "Unity.TextMeshPro.Editor",
        "Unity.Cinemachine.Editor",
        "Unity.Burst.Editor",
        "Unity.Collections.Editor",
        "Unity.Mathematics.Editor",
        "Unity.ProBuilder.Editor",
        "Unity.Splines.Editor",
        "Unity.TerrainTools.Editor",
        "Unity.Timeline.Editor",
        "Den.Tools.Editor",
        "MapMagic.Editor",
        "Autodesk.Fbx.Editor",
        "Unity.Formats.Fbx.Editor",
        "Unity.EditorCoroutines.Editor",
        "ALP8310_ControllerGlobal.Editor"
    ],
    "includePlatforms": [
        "Editor"
    ],
    "excludePlatforms": [],
    "allowUnsafeCode": false,
    "overrideReferences": false,
    "precompiledReferences": [],
    "autoReferenced": true,
    "defineConstraints": [],
    "versionDefines": [],
    "noEngineReferences": false
}
'@
Set-Content -Path $f -Value $json -Encoding UTF8
Write-Host 'Alsasua.Editor.asmdef corregido (sin duplicados).' -ForegroundColor Green
